### ISSUE TITLE
Postgres deadlock observed during concurrent processing

### ISSUE THREAD

**Issue by wotbrew** [xtdb/xtdb#1923]
Running 6 nodes processing a transaction log on a local (docker) postgres:

```
15:59:16.627 [xtdb-tx-processor-30] ERROR xtdb.tx - Ingester error occurred
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 2426 waits for ShareLock on transaction 274376; blocked by process 2425.
Process 2425 waits for ShareLock on transaction 274380; blocked by process 2434.
Process 2434 waits for ExclusiveLock on tuple (245,7) of relation 16966 of database 16964; blocked by process 2426.
  Hint: See server log for query details.
  Where: while locking tuple (245,7) in relation "tx_events"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.result_set$stmt__GT_result_set.invokeStatic(result_set.clj:643)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.result_set$stmt__GT_result_set.invoke(result_set.clj:638)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.result_set$eval6060$fn__6065.invoke(result_set.clj:855)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.protocols$eval5161$fn__5177$G__5150__5186.invoke(protocols.clj:33)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$execute_one_BANG_.invokeStatic(jdbc.clj:269)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$execute_one_BANG_.invoke(jdbc.clj:256)
	at xtdb.jdbc.JdbcDocumentStore$fn__21669.invoke(jdbc.clj:126)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.transaction$eval6247$fn__6248.invoke(transaction.clj:136)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.protocols$eval5251$fn__5252$G__5242__5261.invoke(protocols.clj:57)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$transact.invokeStatic(jdbc.clj:348)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$transact.invoke(jdbc.clj:340)
	at xtdb.jdbc.JdbcDocumentStore.submit_docs(jdbc.clj:118)
	at xtdb.document_store.CachedDocumentStore.submit_docs(document_store.clj:54)
	at xtdb.fork.ForkedDocumentStore.commit_doc_store_tx(fork.clj:162)
	at xtdb.tx.InFlightTx.commit(tx.clj:379)
	at xtdb.tx$__GT_tx_ingester$fn__16918$txs_index_fn__16924.invoke(tx.clj:654)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at xtdb.tx$__GT_tx_ingester$apply_if_not_done__16908.invoke(tx.clj:600)
	at xtdb.tx$__GT_tx_ingester$fn__16918$submit_job_BANG___16919$fn__16920.invoke(tx.clj:635)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Caused by:

```clojure
(conc-run {:sim (counter-sim {:counters 16})
           :pg {}
           :node-count 6
           :submit-threads 1
           :tx-count 10000})
```

Will make more sense once [github.com/wotbrew/xtdb/ ](https://github.com/wotbrew/xtdb/tree/devtool-flake) has a PR, making a note for later investigation.

**Comment by refset** [comment]
Noting that @wotbrew and I heard a report earlier of something similar sounding with MySQL also (unconfirmed, for now)

**Comment by ga-tb** [comment]
That might have been me!

I'll caveat this with: the application I'm working with is one I inherited. I wasn't involved in writing the application code, but I do know we're running `xtdb 1.22.0` and a version of `site` that was forked mid-2022. Database is AWS RDS: `5.7.mysql_aurora.2.10.3`

I have very limited experience with Clojure/Java/JVM :smile_cat: 

The pattern I'm seeing looks like this...

First, a big eviction request. ~100 objects are evicted. (I've replaced the uuid references as they expose some of our internal structures)

```
2023-05-15 07:29:10,589 WARN  juxt.site.alpha.graphql: evicting ([:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] [:xtdb.api/evict [some-data] ) [reqid=/_site/requests/6afa9bab84a75d8b19477989 thread=qtp1242630350-28877]
```

Next, a new transaction, only milliseconds later. In this instance the transaction arrived to the same container as the eviction requests:

```
2023-05-15 07:29:10,722 ERROR xtdb.tx: Ingester error occurred [ thread=xtdb-tx-processor-1] com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
```

It could be a red-herring. There was a second container running at the time, and that was also serving requests, but I've seen this pattern of _evict->deadlock_ in our logs more than once.

**Comment by refset** [comment]
Thanks for chiming in @ga-tb - at least part of the issue with MySQL is resolved now - as per https://github.com/xtdb/xtdb/issues/2546, and we'll capture any new MySQL deadlock issues separately.

**Comment by kevinmershon** [comment]
We are having the same issue on 1.22.2-rc1 with single threaded processing but 4 Kubernetes pods sharing access to the same postgresql golden store.

```
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 3669603 waits for ShareLock on transaction 1523830682; blocked by process 3671419.
Process 3671419 waits for ShareLock on transaction 1523830687; blocked by process 3669603.
  Hint: See server log for query details.
  Where: while locking tuple (4155028,21) in relation "tx_events"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.result_set$stmt__GT_result_set.invokeStatic(result_set.clj:643)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.result_set$stmt__GT_result_set.invoke(result_set.clj:638)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.result_set$eval295573$fn__295578.invoke(result_set.clj:855)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.protocols$eval294674$fn__294675$G__294663__294684.invoke(protocols.clj:33)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$execute_one_BANG_.invokeStatic(jdbc.clj:269)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$execute_one_BANG_.invoke(jdbc.clj:256)
	at xtdb.jdbc.JdbcDocumentStore$fn__296224.invoke(jdbc.clj:126)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.transaction$eval295760$fn__295761.invoke(transaction.clj:136)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.protocols$eval294764$fn__294765$G__294755__294774.invoke(protocols.clj:57)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$transact.invokeStatic(jdbc.clj:348)
	at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$transact.invoke(jdbc.clj:340)
	at xtdb.jdbc.JdbcDocumentStore.submit_docs(jdbc.clj:118)
	at xtdb.document_store.CachedDocumentStore.submit_docs(document_store.clj:54)
	at xtdb.fork.ForkedDocumentStore.commit_doc_store_tx(fork.clj:162)
	at xtdb.tx.InFlightTx.commit(tx.clj:360)
	at xtdb.tx$__GT_tx_ingester$fn__289056$txs_index_fn__289062.invoke(tx.clj:620)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at xtdb.tx$__GT_tx_ingester$apply_if_not_done__289044.invoke(tx.clj:562)
	at xtdb.tx$__GT_tx_ingester$fn__289056$submit_job_BANG___289057$fn__289058.invoke(tx.clj:604)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by refset** [comment]
Hi @kevinmershon thanks for the report. The MySQL-focused change mentioned above _might_ improve things - specifically the [move to `read-committed`](https://github.com/xtdb/xtdb/pull/2547/files#diff-6f53c402a3b5156c07eb4a74a44b4e189981c0f4f2e17d6bb6d563d87c93ff59R118). This change will be released soon. In the meantime, to help confirm the root cause, can you reliably repro the deadlock? And/or can you retrieve additional printout details of the locks? e.g. as per https://severalnines.com/blog/understanding-deadlocks-mysql-postgresql/

**Comment by kevinmershon** [comment]
@refset We've had 36 deadlocks in the last 24 hours across 4 replica k8s pods. It's not happening at a thread-level so it must be occurring internally to postgresql when multiple pods are trying to read the same row (which will happen constantly during our normal data sync operations). Oddly, this problem seems to have manifested when we scaled up from 3 replicas to 4. We have been running 3 replicas for most of 2023 and have been seeing index lock-ups (#1916) at least once a day (often 3+ times a day) but the deadlocking is new. We have not updated or changed our infrastructure otherwise. Today I am scaling back down to 3 replicas to see if the problem ceases. I will follow-up.

Edit: following up, we've had no deadlocks since disabling the 4th replica at 9:20 am today, whereas excluding overnight low volume hours (orange box) the longest duration we'd had for a deadlock was 41 minutes. Having a 4th read replica definitely seems to cause XTDB to deadlock regularly
![image](https://github.com/xtdb/xtdb/assets/812577/bdda67fa-8a50-46ef-9633-703f11dd1dd3)

Edit: following up next day, we have had no deadlocks and only a single reboot due to #1916 Lucene indexing since taking down the 4th read replica.
![image](https://github.com/xtdb/xtdb/assets/812577/a4ecd8a9-5cc6-4fb7-9c50-b93282f183be)

**Comment by kevinmershon** [comment]
It's been some days since taking down our 4th replica. The deadlock has not reappeared although we still see #1916 nearly daily once per pod. The worst times are when all 3 pods hit lucene indexing errors at the same time.

**Comment by wotbrew** [comment]
@kevinmershon I've released [1.23.3](https://github.com/xtdb/xtdb/releases/tag/1.23.3) which contains a fix that might solve your postgres deadlocking problem. If you do try the new release could you feedback whether or not the problem is solved for you?

(I'm not 100% it is fixed for postgres as it was harder for me to repro than MySQL, but it _might_ be)
